name: Deploy to Google Play

on:
  push:
    branches:
      - production  # main 브랜치에 푸시될 때 배포를 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions가 실행될 환경

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. JDK 설정 (필요한 Java 버전 지정)
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # 사용하는 Java 버전

      # 3. Gradle 의존성 캐시
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4. Gradle로 AAB 파일 빌드
      - name: Build AAB
        run: ./gradlew clean bundleRelease

      # 5. Fastlane 설치
      - name: Set up Fastlane
        uses: fastlane/actions/setup-fastlane@v2

      # 6. Fastlane 배포 실행
      - name: Run Fastlane deploy
        run: fastlane deploy
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}  # GitHub Secrets에 저장한 Google Play JSON 키
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # GitHub Secrets에 저장한 Slack Webhook URL
