name: Deploy to Google Play

on:
  push:
    branches:
      - production  # production 브랜치에 푸시될 때 배포를 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions가 실행될 환경

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. JDK 설정 (필요한 Java 버전 지정)
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # 사용하는 Java 버전
          distribution: 'temurin'  # JDK 배포판 (예: 'adoptopenjdk', 'zulu', 'temurin')

      # 2.5 Keystore 디코딩
      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > todolist_keystore.jks
        

      # 3. Gradle 의존성 캐시
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4. Gradle로 AAB 파일 빌드
      - name: Build AAB
        run: ./gradlew clean bundleRelease
        env:
          KEYSTORE_FILE: ../todolist_keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # 5. Fastlane 설치
      - name: Install Fastlane
        run: |
          sudo gem install fastlane -NV

      # 6. Fastlane 배포 실행
      - name: Run Fastlane deploy
        run: fastlane deploy
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}  # GitHub Secrets에 저장한 Google Play JSON 키
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # GitHub Secrets에 저장한 Slack Webhook URL
